# Generated by Django 4.1 on 2023-11-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Город", "verbose_name_plural": "Города"},
        ),
        migrations.AlterModelOptions(
            name="industry",
            options={"verbose_name": "Отрасль", "verbose_name_plural": "Отрасли"},
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="companies.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                null=True, upload_to="companies/logo/", verbose_name="Логотип компании"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="year_founded",
            field=models.PositiveIntegerField(verbose_name="Год основания"),
        ),
    ]
