# Generated by Django 4.1 on 2023-11-14 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favoriteslist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="companies.city",
                verbose_name="Город",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="industries",
            field=models.ManyToManyField(
                related_name="companies",
                to="companies.industry",
                verbose_name="Отрасли",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="services",
            field=models.ManyToManyField(
                related_name="companies", to="companies.service", verbose_name="Услуги"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteslist",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_favorite"
            ),
        ),
    ]
