# Generated by Django 4.1 on 2023-11-17 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteslist',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorite', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(default='undefined', max_length=18),
            preserve_default=False,
        ),
    ]
