# Generated by Django 4.1 on 2023-12-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="companies.city",
                verbose_name="city",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="industries",
            field=models.ManyToManyField(
                related_name="companies",
                to="companies.industry",
                verbose_name="industries",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="services",
            field=models.ManyToManyField(
                related_name="companies",
                to="companies.service",
                verbose_name="services",
            ),
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "company"), name="unique_favorite"
            ),
        ),
    ]
