# Generated by Django 4.1 on 2023-11-20 22:37

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                max_length=254,
                unique=True,
                validators=[users.validators.validate_email_field],
                verbose_name="Почта",
            ),
        ),
    ]
