# Generated by Django 4.1 on 2023-12-05 14:09

from django.db import migrations
import users.model_fields
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=users.model_fields.CustomEmailField(max_length=254, unique=True, validators=[users.validators.UniqueStringInLowercaseValidator(app_label='users', field_name='email', model_name='User')], verbose_name='Почта'),
        ),
    ]
