name: Test when push on all branch

on:
  push:
    branches-ignore:
      - 'main'
      - 'develop'
      - 'release/*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.0 flake8-isort==6.0.0
          pip install -r ./requirements.txt
      - name: Test with flake8
        run:
          python -m flake8 --ignore I001,I004 octopus/
